version: '3.8'

services:
  rabbitmqKonsi:
    image: rabbitmq:management
    ports:
      - "5672:5672" # Porta para comunicação
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

# Outros serviços relacionados (banco de dados, cache, etc.) podem ser adicionados aqui
