version: '3.8'

services:
  rabbitmqKonsi:
    image: rabbitmq:management
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redisKonsi:
    image: redis
    ports:
      - "6379:6379" # Porta Redis
    
  elasticsearchKonsi:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.2
    container_name: elasticsearchKonsi
    environment:
     - xpack.security.enabled=false
     - xpack.security.http.ssl.enabled=false
     - discovery.type=single-node
    ports:
      - "9200:9200"  #HTTP do Elasticsearch
      - "9300:9300"  
